const DataBase = [
    {
        'id': 0,
        "name": "iPhone12",
        "color": ["Red", "Blue", "White"],
        "type": "Mobiles",
        "price": "$450",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count":0,
        "addedToCart": false,
    },
    {
        'id': 1,
        "name": "iPhone11",
        "color": ["Red", "Blue", "White"],
        "type": "Mobiles",
        "price": "$80",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
       "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
         "count":0,
        "addedToCart": false,
    },
    {
        'id': 3,
        "name": "iPhoneX",
        "color": ["Red", "Blue", "White"],
        "type": "Mobiles",
        "price": "$480",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 4,
        "name": "Samsung Galaxy fold",
        "color": ["Red", "Blue", "White"],
        "type": "Mobiles",
        "price": "$1280",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count":0,
        "addedToCart": false,
    },
    {
        'id': 5,
        "name": "Sony experia",
        "color": ["Red", "Blue", "White"],
        "type": "Mobiles",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },

    {
        'id': 6,
        "name": "Hp Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Laptops",
        "price": "$250",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 7,
        "name": "Dell Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Laptops",
        "price": "$80",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 8,
        "name": "Acer Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Laptops",
        "price": "$480",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 9,
        "name": "Asus Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Laptops",
        "price": "$1280",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 10,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Laptops",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 11,
        "name": "Sony Bravia",
        "color": ["Red", "Blue", "White"],
        "type": "Televisions",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 12,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Televisions",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 13,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Televisions",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 14,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Televisions",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 15,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Televisions",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 16,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Headphones/Earphones",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 17,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Headphones/Earphones",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 18,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Headphones/Earphones",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 19,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Headphones/Earphones",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 20,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Headphones/Earphones",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 21,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Computer accessories",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 22,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Computer accessories",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 23,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Computer accessories",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 24,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Computer accessories",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 25,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Mobile accessories",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 26,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Watches",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 27,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Watches",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 28,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Watches",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 29,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Watches",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 30,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Watches",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 31,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Storage Devices",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 32,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Storage Devices",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 33,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Storage Devices",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 34,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Storage Devices",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 35,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Storage Devices",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 36,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Cameras",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 37,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Cameras",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 38,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Cameras",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 39,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Cameras",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 40,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Cameras",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 41,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Home Appliances",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 42,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Home Appliances",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 43,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Home Appliances",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 45,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Home Appliances",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 46,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Air Conditioners",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 47,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Air Conditioners",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 48,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Kitchen Appliances",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 49,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Kitchen Appliances",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 50,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Kitchen Appliances",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 51,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Kitchen Appliances",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 52,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Vehicle appliances",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 53,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Vehicle appliances",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 54,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Vehicle appliances",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 55,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Kids Section",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 56,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Electricals",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    }, {
        'id': 57,
        "name": "Mi Laptop",
        "color": ["Red", "Blue", "White"],
        "type": "Gardening tools",
        "price": "$380",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "3",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },













    {
        'id': 58,
        "name": "iPhone12",
        "color": ["Red", "Blue", "White"],
        "type": "Mobiles",
        "price": "$450",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 59,
        "name": "iPhone12",
        "color": ["Red", "Blue", "White"],
        "type": "Mobiles",
        "price": "$450",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 60,
        "name": "iPhone12",
        "color": ["Red", "Blue", "White"],
        "type": "Mobiles",
        "price": "$450",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 61,
        "name": "iPhone12",
        "color": ["Red", "Blue", "White"],
        "type": "Mobiles",
        "price": "$450",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 62,
        "name": "iPhone12",
        "color": ["Red", "Blue", "White"],
        "type": "Mobiles",
        "price": "$450",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },
    {
        'id': 63,
        "name": "iPhone12",
        "color": ["Red", "Blue", "White"],
        "type": "Mobiles",
        "price": "$450",
        "description": ["6.1-inch (15.5 cm) Liquid Retina HD LCD display", "Water and dust resistant (2 meters for up to 30 minutes, IP68)", "Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps", "12MP TrueDepth front camera with Portrait mode, 4K video, and Slo-Mo", "Face ID for secure authentication", "A13 Bionic chip with third-generation Neural Engine", "Fast-charge capable", "Wireless charging", "As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately", "iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more"],
        "rating": "4",
        "totalRating": "5",
        "img": ["https://drop.ndtv.com/TECH/product_database/images/913201720152AM_635_iphone_x.jpeg?downsize=*:180&output-quality=80&output-format=webp", "https://static.quickmobileshop.com/cs-photos/products/original/iphone-7-128gb-lte-4g-silver_10011929_1_1473693519.jpg"],
        "count": 0,
        "addedToCart": false,
    },





]




export default DataBase